name: deploy

on:
  push:
    branches:
    - main

  workflow_dispatch:

jobs:
  build:
    name: Build Docker image and upload to Github Container Registry
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build and push image to Google Container Registry
      - name: Build and push
        run: |
          docker build \
            --build-arg COMMIT=${GITHUB_SHA:0:7} \
            --build-arg LASTMOD=$(date -u +%Y-%m-%dT%H:%M:%SZ) \
            --push \
            --tag ghcr.io/fileformat/node-without-npm:$GITHUB_SHA \
            --tag ghcr.io/fileformat/node-without-npm:latest \
            .

